[theme]

# Primary accent for interactive elements
primaryColor = 'rgb(254, 245,255)'

# Background color for the main content area
backgroundColor = '#273346'
# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#aba999'

# Color used for almost all text
textColor = '#255 255 255'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"





